### PR TITLE
Create repoman.yaml

### PR DESCRIPTION
**Pull request by jeffmay**
@danstaley @patrick-bohan

### CODE REVIEW

**Comment by danstaley** [comment]
(derp) there is no way I would have caught that.
Anyway, LGTM once the name is correct.

**Comment by jeffmay** [comment]
Woah... all this time I thought the extension was `.yml`

http://stackoverflow.com/questions/21059124/is-it-yaml-or-yml

**Comment by patrick-bohan** [comment]
> Woah... all this time I thought the extension was .yml

I think .yml is a valid extension -- but repoman does not look for that, it looks for explicitly .yaml. I found out because I did the same thing for lib-carestats.

**Comment by jeffmay** [comment]
@patrick-bohan fixed.

**Pull request merged**
